### ISSUE TITLE
[PE-D][Tester B] Calories list does not differentiate between calories in and out

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-F15-2/tp#115]
![image.png](https://raw.githubusercontent.com/Hws2209/ped/main/files/d63a7dcb-230a-41be-9003-775ae0ed561b.png)
Users of this product would probably want to be able to easily tell/compare the calories in and out, instead of having to read every description and decide on their own.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Hws2209/ped#2

**Comment by rexyyong** [comment]
Issue has been raised elsewhere, will fix it thank you :)
