### ISSUE TITLE
[PE-D][Tester B] "sleep add" shows error message even when the example inputs from UG is used

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-F15-2/tp#119]
![image.png](https://raw.githubusercontent.com/Hws2209/ped/main/files/ccd70d7d-abb1-4672-a0e7-f8cdd015bd28.png)

Example inputs from the user guide were used but the numbers are not considered as positive real numbers by the app.
Not too sure if this is a bug in functionality or the UG is not updated?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Hws2209/ped#4

**Comment by rexyyong** [comment]
Thank you, has been fixed
