### ISSUE TITLE
[PE-D][Tester D] Invalid Date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-F15-2/tp#121]
![image.png](https://raw.githubusercontent.com/anneleong/ped/main/files/94d812b9-b1e9-4d8c-ba29-d2a7a1c9676e.png)

User provided a date later than the current date but exception is not caught

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: anneleong/ped#3

**Comment by rexyyong** [comment]
Fix for this

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/1fe4e648-858e-46b5-9fe2-1fd8a858d655)
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/12e87ce4-fd0d-4915-bab9-12a86c774b5f)

**Comment by rexyyong** [comment]
@a-wild-chocolate  @shawnpong  I realised this issue is relevant to the both of yall also. Remember to edit accordingly. I have assigned yall also.

**Comment by a-wild-chocolate** [comment]
Thanks, I fixed the same bug for sleep entry

**Comment by shawnpong** [comment]
Added to hydration
