### ISSUE TITLE
[PE-D][Tester A] Printing unexpected error message when the date format is not correct

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-F15-2/tp#123]
![image.png](https://raw.githubusercontent.com/BestDownLoader365/ped/main/files/193f804d-eecf-4ddb-8b4a-017bd57d5e58.png)

When the date format is wrong, the system will print internal error message which is not expected

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: BestDownLoader365/ped#1

**Comment by owx0130** [comment]
closing this as @a-wild-chocolate has fixed it
