### ISSUE TITLE
[PE-D][Tester C] Sleep per day can exceed 24 hours

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-F15-2/tp#144]
![image.png](https://raw.githubusercontent.com/JackieNeoCEG/ped/main/files/7b2e110c-ff8c-4f6c-90f4-e94e5b7b60d6.png)

1. User can input total of 26.5 hours of sleep on `2024-03-01`, which is not possible in real life.

![image.png](https://raw.githubusercontent.com/JackieNeoCEG/ped/main/files/980ff18e-819b-48f1-866f-bccc3da1086b.png)

2. User can also input more than 24 hours of sleep in a day, which is also not possible.

Improvement: Implement a stopping condition if hours exceed 24 hours in the input.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: JackieNeoCEG/ped#9

**Comment by a-wild-chocolate** [comment]
Thank you, the issue has been solved, now sleep duration limit is 24 hours.
