### ISSUE TITLE
Add only entries from the current day onto the calorie progress bar and hydration progress bar

### ISSUE THREAD

**Issue by paturikarthik** [AY2324S2-CS2113-F15-2/tp#178]
@shawnpong @rexyyong Please help to ensure that only entries from the current day are reflected for the calorie and hydration progress bars. They can be found in `getCaloriesConsumed` in `CalorieList` and `getHydrationConsumed` in `HydrationList` respectively.

**Comment by shawnpong** [comment]
Doned
