### ISSUE TITLE
[Internal Testing] hydrationID does not increment correctly

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-F15-2/tp#186]
Input: hydration in mil1239182398 asjdnclaks jdn19o38y4o unsladkjcn 9o13874 yhkjn v/1 d/2024-04-03

Expected output: hydration entry added with correct increment of hydrationID

actual output: 
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/ff873bf3-6330-422d-bfcd-cdeda2e52495)

tried it again and
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/62fd8a70-9476-4595-857b-6185564dc9f8)

Cause of issue: when app is launched, the hydrationID should be updated based on the lastEntry. the hydrationID should not be set back to 1

**Comment by owx0130** [comment]
this has been fixed in PR #218
