### ISSUE TITLE
[Internal testing] more robust exception message for hydration in command required

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-F15-2/tp#187]
Input: hydration in cum v/100 v/100 d/2024-04-03

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/70e270c4-12e5-4fe6-ab39-e5495e68c00c)

Maybe exception message shoudl say something like too many parameters entered? idk

**Comment by rexyyong** [comment]
Refer to this for a good example of what should be displayed i guess

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/edce243a-8f61-4279-be6a-638066412358)

**Comment by shawnpong** [comment]
Done in #258

**Comment by rexyyong** [comment]
also fixed it for this case
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/cad5c194-56f9-4d38-9f11-aef3abc81a30)
