### ISSUE TITLE
[Internal testing] Does spacing for commands matter or not

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-F15-2/tp#188]
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/df5b2b3f-31e0-42b3-9258-327b7d3bd6d6)
Perssonally i feel its fine but do yall wanna allow users to input the command without spaces, example 
hydration in milo v/10000 d/2024-04-12
versus
hydration inmilov/10000d/2024-04-12

**Comment by owx0130** [comment]
we can leave this issue open for now, but i agree quite low priority imo, can fix if we got nothing else to fix

**Comment by paturikarthik** [comment]
I feel this is okay. The premise of the app is that the user is a fast typer.

**Comment by rexyyong** [comment]
agree with karthik, if all agreeble we can clsoe this

**Comment by shawnpong** [comment]
i agree with paturai
