### ISSUE TITLE
[internal testing] wrong hydration list command allows hydration list to be listed

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-F15-2/tp#190]
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/03c55549-58fb-45d6-a78c-8ecf31ef4f38)
need to make sure this throws an exception. force users to type hydration list strictly i guess

**Comment by shawnpong** [comment]
@paturikarthik already fixed this, thanks <3
