### ISSUE TITLE
[Internal Testing] spacing issue for hydration delete

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-F15-2/tp#192]
Do we want to allow users to delete if they did not have a spacing between delete and 4

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/7c623012-b1f8-4de8-8a45-f1e683fc2b5f)

**Comment by shawnpong** [comment]
As far as i can see, this is not allowed, will close this issue for now
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/110764881/c44a4c9c-eaa6-4cc1-885f-0d9a27267977)
