### ISSUE TITLE
[Internal Testing] exception message for hydration delete wrong

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-F15-2/tp#193]
should be 
 The following hydration record corresponding to **_hydrationID_** 10 could not be found

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/fdef4b86-e67e-45ce-bd70-c8b57bb68f4b)

**Comment by shawnpong** [comment]
Thanks for the heads up!
