### ISSUE TITLE
[Internal Testing] display of sleep duration if duration is only 1 min

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-F15-2/tp#195]
I know this sounds ridiculous but will they flag this as a bug? 

What if i nap for 1 minute, it is shown as duration 0.0 hours. Should we make it 2 dp instead?
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/3c127713-4d2e-4517-ac34-c78fef942571)

**Comment by owx0130** [comment]
ok just display as 2d.p to avoid trouble @a-wild-chocolate

**Comment by rexyyong** [comment]
I change to 2 dp 
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/79166631-c3b4-40b5-a896-f0a78e28a282)

**Comment by rexyyong** [comment]
PR #246
