### ISSUE TITLE
[Internal Testing] Invalid sleep list command

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-F15-2/tp#196]
This should throw an exception. force users to type in correct command which is sleep list

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/6551e282-bf39-4a21-9dfa-ac755b7fe5ba)

**Comment by a-wild-chocolate** [comment]
This issue could be fixed in Ui, when handleSleepInput() use equals rather than start with, same as other handle input.
