### ISSUE TITLE
[Internal Testing] sorting of sleep array list

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-F15-2/tp#197]
Should we sort the dates in sleep list as well? not really a bug but an enhancement

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/3c757d83-b2cc-4f60-b9b0-393a96bf50f7)

For example if we look at calories list, all the entries are sorted in ascending order
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/e3772541-ba90-444f-b063-bb8465abd3fa)

**Comment by paturikarthik** [comment]
Yes we should. It will create consistency in the app. However, @a-wild-chocolate if you dont have enough time its fine! can also ask @rexyyong for help since he did the sorting before

**Comment by rexyyong** [comment]
Add fix
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/0671dd72-440b-4cb4-822e-be47ab2b9017)

**Comment by rexyyong** [comment]
PR #246
