### ISSUE TITLE
[Internal Testing] Should we sort hydration by date

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-F15-2/tp#198]
Same thing for hydration, should we sort the hydration list by date. 
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/3895baba-3dec-4d8e-b807-a41af1d5135c)

**Comment by owx0130** [comment]
yes we should, can @a-wild-chocolate and @shawnpong work on this

**Comment by rexyyong** [comment]
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/6ea42490-2cad-4db5-9855-4be2c181a81c)
Sorting works on latest version #225
