### ISSUE TITLE
[Internal Testing] Potential issue for progress bar for sleep to make sense

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-F15-2/tp#200]
@paturikarthik  idh the most updated version of what you did in sbux yesterday. 

But the gist of it is, for example if you look at sleep list, for 2024-04-13, the sleep hours exceed 24 hours, 23 + 23 = 46
Will there be a problem if i call user progress, and sleep progress bar exceeds 100%

cuz logically speaking the sleep cannot be more than 24 hours a day to begin with ukwim

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/19182422-b5b1-4419-a3ac-fa358c47193f)

**Comment by paturikarthik** [comment]
Good Catch @rexyyong ! Taken care of during the input from the user itself by handling the exception as such.
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/64789669/e75138e1-d0ab-4a43-bec6-ee1a78de515b)
