### ISSUE TITLE
[Internal Testing] program crashes upon entering "sleep delete"

### ISSUE THREAD

**Issue by owx0130** [AY2324S2-CS2113-F15-2/tp#204]
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/110607839/7673a770-6fe1-438f-b994-063a5209e097)

@a-wild-chocolate urgent bug to fix, program will crash when user just inputs `sleep delete`.

**Comment by a-wild-chocolate** [comment]
Noted, fixed the issue already. Thank you!
