### ISSUE TITLE
[Internal Testing] Repeated Error Message for calories in non-integer input

### ISSUE THREAD

**Issue by paturikarthik** [AY2324S2-CS2113-F15-2/tp#205]
When calories in has non-integer input, the error message is shown twice.

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/64789669/4af066ad-fc52-4dea-ab06-ba2b8a974a14)

**Comment by rexyyong** [comment]
Fix printing
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/55968624-d95c-4fa7-847f-c25a987af81e)

**Comment by rexyyong** [comment]
PR #246
