### ISSUE TITLE
[Internal Testing] No error handling for unrealistic calories input

### ISSUE THREAD

**Issue by paturikarthik** [AY2324S2-CS2113-F15-2/tp#206]
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/64789669/e5ee9bc3-e3c9-470a-9ef8-61d54b34580a)
 
I think we should add limit to the number of calories possible to input. Given that the average daily intake should be roughly 2k, we can possibly add an upper limit of 4000 calories to play it safe? Even Lower also makes sense to me. @rexyyong @owx0130 what do you guys think?

**Comment by rexyyong** [comment]
Add limit of 5k for calories in
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/3cdbbd3d-5d39-4002-a847-59a2f86837b9)

**Comment by rexyyong** [comment]
Add limit of 5k for calories out as well
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/6ff3277a-8d36-4cec-8736-7defe7b8b1ba)

**Comment by rexyyong** [comment]
PR #246
