### ISSUE TITLE
[Internal Testing] No limit to beverage volume

### ISSUE THREAD

**Issue by paturikarthik** [AY2324S2-CS2113-F15-2/tp#210]
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/64789669/76a096f4-7243-4d84-afe8-2a6bf39653cd)

Should there be a limit to the amount of beverage a user can drink? Protects us against a user who tries to enter a number close to or above the `MAX_INT`. @owx0130 @shawnpong thoughts?

**Comment by shawnpong** [comment]
I will enforce volume to be not more than 10000 ml

**Comment by shawnpong** [comment]
Have since updated user guide to specify volume should not be more than 10000 ml, updated code accordingly
