### ISSUE TITLE
[Internal Testing] Inconsistency in SleepID

### ISSUE THREAD

**Issue by paturikarthik** [AY2324S2-CS2113-F15-2/tp#216]
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/64789669/291455ec-46f4-4916-8bdd-f2fd228eb420)
Here, the sleepID is 0, however, the UG states that sleepID should start from 1 onwards.
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/64789669/35d459d6-817d-4d59-869c-2b4dfb737ec9)

**Comment by a-wild-chocolate** [comment]
Noted, sleep id changed to start from 1 now.
