### ISSUE TITLE
[Peer Testing] Current command handling only checks if the command string is contained within the user's input in the beginning

### ISSUE THREAD

**Issue by seandooa** [AY2324S2-CS2113-F15-2/tp#226]
For commands like help and sleep list, typing "helpeirfu3riuf3fiu3h" or "sleep listing" or "sleep list wijfweiofjweif" are also accepted commands. Not sure if this is intended though as it could be argued that having those words in the input means the user intends to use those commands already.

Same behaviour can be observed for other commands like user details and user progress.

**Comment by shawnpong** [comment]
hehe
