### ISSUE TITLE
[Peer Testing] Limit calorie count

### ISSUE THREAD

**Issue by liuy1103** [AY2324S2-CS2113-F15-2/tp#228]
Perhaps can consider setting a limit to the maximum calorie entry? Minor issue though. (Based on google "adults typically require between 1,600–3,000 calories per day", so perhaps the hard limit can be about 8-10k or something)
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/111263614/bb5a3552-7122-48ab-a9d0-66149092b62a)

**Comment by rexyyong** [comment]
fixed at PR #246 
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/4c24b3a8-fbf8-496b-af31-c1a3f6bf8b79)
