### ISSUE TITLE
[Peer Testing] "calories in" function allows for negative proteins

### ISSUE THREAD

**Issue by soongensayo** [AY2324S2-CS2113-F15-2/tp#232]
<img width="771" alt="Screenshot 2024-04-14 at 8 32 14 PM" src="https://github.com/AY2324S2-CS2113-F15-2/tp/assets/110648719/6f840088-a836-48bd-9207-8730dbcdc282">

**Comment by owx0130** [comment]
issue has been fixed, thanks!
