### ISSUE TITLE
[Peer Testing] Allow no spaces between calories in command

### ISSUE THREAD

**Issue by liuy1103** [AY2324S2-CS2113-F15-2/tp#234]
Not sure if this was intended but users are able to input the values without a spacing. The app still gives the correct output though.

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/111263614/0f2e49b3-ba8f-4073-96f0-3f83c5fd0a1d)

**Comment by rexyyong** [comment]
@paturikarthik  @owx0130  think we discussed that we will allow this? for the sake of fast typing

**Comment by paturikarthik** [comment]
I am agreeable to this!

**Comment by rexyyong** [comment]
According to this i think we allow and can close this issue
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/84d76791-72b9-4c6f-8187-652f09cfaa6e)
