### ISSUE TITLE
[Peer Testing] User Guide Command Unclear

### ISSUE THREAD

**Issue by tiffanyliu0220** [AY2324S2-CS2113-F15-2/tp#238]
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/110823843/84a4eae1-abba-42d0-8d0d-c9f50bce9060)
under the section for sleep list:
perhaps should specify it to be 'sleep list' instead of just 'list'
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/110823843/2e82afa6-7cd0-4296-88ea-789579ab1fe5)

**Comment by a-wild-chocolate** [comment]
Thank you for your suggestion, this command has been modified.
