### ISSUE TITLE
[Peer Testing] make clearer explanations in UG

### ISSUE THREAD

**Issue by tiffanyliu0220** [AY2324S2-CS2113-F15-2/tp#240]
after i deleted calories index 3, when i add a new item to calories in, the index is 4 instead of 3. Perhaps you can include that in the user guide so that users know that the index adds on to the previous one, even if that is deleted.
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/110823843/4a91e831-1478-4744-96f4-a4a01c288610)

**Comment by rexyyong** [comment]
@owx0130  
can help me see if this is clear enough

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/6181e960-66a4-4797-a0cc-403be0b02551)
