### ISSUE TITLE
[Peer Testing] Error message appeared twice

### ISSUE THREAD

**Issue by tiffanyliu0220** [AY2324S2-CS2113-F15-2/tp#244]
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/110823843/fef05b5c-79fe-4ffe-a67e-3564d689c582)
not sure if this is intended

**Comment by rexyyong** [comment]
fixed at pr #246 
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/9636cfd2-d71d-4eeb-a917-612970e23ee8)
