### ISSUE TITLE
[Peer Testing] large inputs are acceptable

### ISSUE THREAD

**Issue by tiffanyliu0220** [AY2324S2-CS2113-F15-2/tp#245]
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/110823843/e48b3d30-ca3d-45f0-b46a-b300f212bde7)
not sure if you want to allow such large inputs

**Comment by rexyyong** [comment]
fixed at pr #246 
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/c0d8fd69-dbcb-43ba-adbb-1b33a9a86af3)
