### ISSUE TITLE
[Peer Testing] No proper handling of large inputs

### ISSUE THREAD

**Issue by RyanTDL** [AY2324S2-CS2113-F15-2/tp#251]
![Screenshot 2024-04-15 001751](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/113768146/2f9439a5-ecc9-4b7e-a27b-98c31a3700c9)

Perhaps set a limit to the 'calorie' and 'macronutrients' fields

**Comment by rexyyong** [comment]
Limit for calories set at PR #246 . Now i need to set for macros as well

**Comment by owx0130** [comment]
@shawnpong @a-wild-chocolate relevant to yall also

**Comment by shawnpong** [comment]
i have set the volume maximum to 10000 as in PR #225

**Comment by rexyyong** [comment]
Deciding macros limits. I shall limit them to 800 g per entry
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/914a28a1-f86f-47c9-9b1e-58741ca29a5b)
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/2fb6deea-d148-49a7-85e4-4c5e8434d0e1)
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/889a582d-0a8a-4af8-82f7-4b727ba1f4e3)

**Comment by rexyyong** [comment]
Fix macro issue
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/b5e3a1bf-0cc5-4e92-ad2c-3fd439403034)

**Comment by a-wild-chocolate** [comment]
sleep have a maximum limit 24 hours pre day
