### ISSUE TITLE
[Peer Testing] Incorrect error message

### ISSUE THREAD

**Issue by RyanTDL** [AY2324S2-CS2113-F15-2/tp#252]
![Screenshot 2024-04-15 001708](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/113768146/a573d24d-e110-44c8-8a53-20553a6abdc1)

Pass a certain positive integer, error message appears twice, informing me that only positive integers are allowed. Not sure why the message appears twice, but I am assuming the number is registered as a negative due to data type overflow error. Proper handling needed for this scenario

**Comment by rexyyong** [comment]
thanks. Fixed at pr #246 
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/76645229/1eebf068-2be7-458c-b058-59349e86a0e1)
