### ISSUE TITLE
[Peer Testing] No proper error handling for date input

### ISSUE THREAD

**Issue by RyanTDL** [AY2324S2-CS2113-F15-2/tp#253]
![Screenshot 2024-04-15 003118](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/113768146/4718b17d-8edb-483e-8513-1d8930da0a03)

Inputting the date halfway, using 'd/' instead of 'd/2022-03-23' results in error

**Comment by shawnpong** [comment]
settled! thanks
