### ISSUE TITLE
Add hydration in command to track water intake

### ISSUE THREAD

**Issue by shawnpong** [AY2324S2-CS2113-F15-2/tp#34]
As a busy student I can register my water intake by inputting the amount of water i consume throughout the day

**Comment by owx0130** [comment]
basic functionality done, keeping issue open for further integration with calories tracker

**Comment by rexyyong** [comment]
basic features met, may need to make the following improvements

1. Include date
2. Change the input command for liquids in. For example, change from liquids in b/BEVERAGE v/VOLUME to liquids in BEVERAGE v/VOLUME d/DATE

**Comment by owx0130** [comment]
above mentioned improvements have been completed, closing this now
