### ISSUE TITLE
Add exception handling for Class ParserCalories.java

### ISSUE THREAD

**Issue by rexyyong** [AY2324S2-CS2113-F15-2/tp#44]
Add exceptions

Exception for keying in macro field correctly
Exception for ensuring all macronutrients have been typed in
Exception for keying in macros with spaces in inputs
Exception for ensuring that there are no blanks in macronutrients fields
Exception to handle case where calories out commands are entered in wrong order
Exception to handle case where calories in commands are entered in wrong order
Exception to handle unexpected case of keying in macros for calories out

**Comment by owx0130** [comment]
feature completed and merged into codebase
