### ISSUE TITLE
[Code Review] shawnpong

### ISSUE THREAD

**Issue by nichyjt** [AY2324S2-CS2113-F15-2/tp#87]
### AFI (Code Quality)
Under `ParserHydration`:
![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/69704055/dda17bf5-6528-4425-be9e-10e68167f5ce)

1. Good that you used assertions. But it is not entirely clear what `parts[1]` and `parts[2]` mean to someone reading the codebase. Factor out the magic literals. This applies to the rest of the file as well!

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/69704055/2d24d039-f41e-425b-b00a-c89a9ada7326)
1. Could there be a more direct way of expressing this inequality? 

Good that you've used asserts to check underlying assumptions about the code. Remember to factor out your literals. All the best!

**Comment by shawnpong** [comment]
Thank you!
