### ISSUE TITLE
[Code Review] rexyyong

### ISSUE THREAD

**Issue by nichyjt** [AY2324S2-CS2113-F15-2/tp#88]
### AFI (Code Quality)

![image](https://github.com/AY2324S2-CS2113-F15-2/tp/assets/69704055/a40f396c-d04e-4de5-b96a-6db6b3160071)
1. I is not entirely clear what parts[1] and parts[2] mean to someone reading the codebase. Factor out the magic literals. This applies to the rest of the file as well!

Please take note of the magic literal issue across the codebase. All the best!

**Comment by rexyyong** [comment]
Thank you for the review, will take not of the magic literals
